In [2]:
import pandas as pd
import numpy as np

# **Missing Value Handle**

# **{"Key": ["value", "value", "value"]}**

In [ ]:
dataset = {"Name" : ["Ratul", "Fahmid", "Tahfim", "Atik"],
           "Age" : [25, np.nan, 25, np.nan],
           "Salary" : [50000, 35000, np.nan, 44000],
           "Gender" : ['M','M', np.nan, 'M']
           }

In [ ]:
dataset

{'Name': ['Ratul', 'Fahmid', 'Tahfim', 'Atik'],
 'Age': [25, nan, 25, nan],
 'Salary': [50000, 35000, nan, 44000],
 'Gender': ['M', 'M', nan, 'M']}

# **Table Format**

In [ ]:
df = pd.DataFrame(dataset)
df

     Name   Age   Salary Gender
0   Ratul  25.0  50000.0      M
1  Fahmid   NaN  35000.0      M
2  Tahfim  25.0      NaN    NaN
3    Atik   NaN  44000.0      M

In [ ]:
df.isnull().sum() #check missing value

Name      0
Age       2
Salary    1
Gender    1
dtype: int64

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Age']

0    25.0
1    25.0
2    25.0
3    25.0
Name: Age, dtype: float64

In [ ]:
df

     Name   Age   Salary Gender
0   Ratul  25.0  50000.0      M
1  Fahmid  25.0  35000.0      M
2  Tahfim  25.0      NaN    NaN
3    Atik  25.0  44000.0      M

In [ ]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [ ]:
df

     Name   Age   Salary Gender
0   Ratul  25.0  50000.0      M
1  Fahmid  25.0  35000.0      M
2  Tahfim  25.0  44000.0    NaN
3    Atik  25.0  44000.0      M

In [ ]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [ ]:
df

     Name   Age   Salary Gender
0   Ratul  25.0  50000.0      M
1  Fahmid  25.0  35000.0      M
2  Tahfim  25.0  44000.0      M
3    Atik  25.0  44000.0      M

# **Encoding: Lebel Encoding.**

# **Group By Analysis**

In [3]:
sales = pd.DataFrame({
    "City" : ["Dhaka", "Dhaka", "Dhaka", "Dhaka", "Dhaka"],
    "Category" : ['Laptop', 'Mouse', 'Mouse', 'Laptop', 'Laptop'],
    "Sales" : [20000, 4000, 3000, 30000, 50000]
})

In [4]:
sales

    City Category  Sales
0  Dhaka   Laptop  20000
1  Dhaka    Mouse   4000
2  Dhaka    Mouse   3000
3  Dhaka   Laptop  30000
4  Dhaka   Laptop  50000

In [5]:
sales.groupby('City')['Sales'].mean()

City
Dhaka    21400.0
Name: Sales, dtype: float64